// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taskama.Context;

#nullable disable

namespace Taskama.Migrations
{
    [DbContext(typeof(TaskamaContext))]
    [Migration("20241204063826_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Taskama.Pages.Model.Comment", b =>
                {
                    b.Property<Guid>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("taskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("commentId");

                    b.HasIndex("taskId");

                    b.HasIndex("userId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Taskama.Pages.Model.Project", b =>
                {
                    b.Property<Guid>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("projectId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Taskama.Pages.Model.ProjectMember", b =>
                {
                    b.Property<Guid>("projectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("projectId", "userId");

                    b.HasIndex("userId");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("Taskama.Pages.Model.Tag", b =>
                {
                    b.Property<Guid>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("taskId");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("Taskama.Pages.Model.Task", b =>
                {
                    b.Property<Guid>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("assignedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("createdAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("projectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("taskId");

                    b.HasIndex("assignedToId");

                    b.HasIndex("projectId");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("Taskama.Pages.Model.TaskTag", b =>
                {
                    b.Property<Guid>("tagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("taskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("tagId", "taskId");

                    b.HasIndex("taskId");

                    b.ToTable("TaskTag");
                });

            modelBuilder.Entity("Taskama.Pages.Model.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("userId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Taskama.Pages.Model.UserProfile", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("avatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Taskama.Pages.Model.Comment", b =>
                {
                    b.HasOne("Taskama.Pages.Model.Task", "task")
                        .WithMany("Comments")
                        .HasForeignKey("taskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taskama.Pages.Model.User", "user")
                        .WithMany("comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("task");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Taskama.Pages.Model.ProjectMember", b =>
                {
                    b.HasOne("Taskama.Pages.Model.Project", "project")
                        .WithMany("members")
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taskama.Pages.Model.User", "user")
                        .WithMany("projectMembers")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Taskama.Pages.Model.Task", b =>
                {
                    b.HasOne("Taskama.Pages.Model.User", "assignedTo")
                        .WithMany("assignedTasks")
                        .HasForeignKey("assignedToId");

                    b.HasOne("Taskama.Pages.Model.Project", "project")
                        .WithMany("tasks")
                        .HasForeignKey("projectId");

                    b.Navigation("assignedTo");

                    b.Navigation("project");
                });

            modelBuilder.Entity("Taskama.Pages.Model.TaskTag", b =>
                {
                    b.HasOne("Taskama.Pages.Model.Tag", "tag")
                        .WithMany("taskTags")
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taskama.Pages.Model.Task", "task")
                        .WithMany("TaskTags")
                        .HasForeignKey("taskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tag");

                    b.Navigation("task");
                });

            modelBuilder.Entity("Taskama.Pages.Model.UserProfile", b =>
                {
                    b.HasOne("Taskama.Pages.Model.User", "user")
                        .WithOne("userProfile")
                        .HasForeignKey("Taskama.Pages.Model.UserProfile", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Taskama.Pages.Model.Project", b =>
                {
                    b.Navigation("members");

                    b.Navigation("tasks");
                });

            modelBuilder.Entity("Taskama.Pages.Model.Tag", b =>
                {
                    b.Navigation("taskTags");
                });

            modelBuilder.Entity("Taskama.Pages.Model.Task", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TaskTags");
                });

            modelBuilder.Entity("Taskama.Pages.Model.User", b =>
                {
                    b.Navigation("assignedTasks");

                    b.Navigation("comments");

                    b.Navigation("projectMembers");

                    b.Navigation("userProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
